/* Generated by re2c 1.0.3 on Thu Apr 12 19:40:04 2018 */
#line 1 "integers.re"
#include <stdio.h>

enum num_t 
{
    ERR, // 错误
    BIN, // 二进制
    OCT, // 八进制
    DEC, // 十进制
    HEX  // 十六进制
};

typedef enum num_t num_t_t;

// 这里原来返回是 `static num_t lex`，但是使用 vscode 的时候会提示有问题
// 经过查资料，https://stackoverflow.com/questions/1102542/how-to-define-an-enumerated-type-enum-in-c
// 默认使用是需要使用 enum 作为前缀的，如果不想使用的话，可以使用 typeof
static enum num_t lex(const char *YYCURSOR)
{
    const char *YYMARKER;
    
#line 24 "integers.cc"
{
	char yych;
	yych = *YYCURSOR;
	switch (yych) {
	case '0':	goto yy4;
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy5;
	default:	goto yy2;
	}
yy2:
	++YYCURSOR;
yy3:
#line 30 "integers.re"
	{ return ERR; }
#line 46 "integers.cc"
yy4:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 0x00:	goto yy6;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':	goto yy8;
	case 'B':
	case 'b':	goto yy11;
	case 'X':
	case 'x':	goto yy12;
	default:	goto yy3;
	}
yy5:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 0x00:	goto yy13;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy15;
	default:	goto yy3;
	}
yy6:
	++YYCURSOR;
#line 32 "integers.re"
	{ return OCT; }
#line 85 "integers.cc"
yy8:
	yych = *++YYCURSOR;
	switch (yych) {
	case 0x00:	goto yy6;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':	goto yy8;
	default:	goto yy10;
	}
yy10:
	YYCURSOR = YYMARKER;
	goto yy3;
yy11:
	yych = *++YYCURSOR;
	if (yych <= 0x00) goto yy10;
	goto yy18;
yy12:
	yych = *++YYCURSOR;
	if (yych <= 0x00) goto yy10;
	goto yy20;
yy13:
	++YYCURSOR;
#line 33 "integers.re"
	{ return DEC; }
#line 115 "integers.cc"
yy15:
	yych = *++YYCURSOR;
	switch (yych) {
	case 0x00:	goto yy13;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy15;
	default:	goto yy10;
	}
yy17:
	yych = *++YYCURSOR;
yy18:
	switch (yych) {
	case 0x00:	goto yy21;
	case '0':
	case '1':	goto yy17;
	default:	goto yy10;
	}
yy19:
	yych = *++YYCURSOR;
yy20:
	switch (yych) {
	case 0x00:	goto yy23;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy19;
	default:	goto yy10;
	}
yy21:
	++YYCURSOR;
#line 31 "integers.re"
	{ return BIN; }
#line 174 "integers.cc"
yy23:
	++YYCURSOR;
#line 34 "integers.re"
	{ return HEX; }
#line 179 "integers.cc"
}
#line 35 "integers.re"

}

static num_t_t lexNew(const char *YYCURSOR)
{
    return lex(YYCURSOR);
}

int main(int argc, char **argv)
{
    for (int i = 1; i < argc; ++i) {
        switch (lexNew(argv[i])) {
            case ERR: printf("错误\n"); break;
            case BIN: printf("二进制\n"); break;
            case OCT: printf("八进制\n"); break;
            case DEC: printf("十进制\n"); break;
            case HEX: printf("十六进制\n"); break;
        }
    }
    return 0;
}
